import streamlit as st
import requests
from openai import OpenAI
import re

# Initialize session state
if "email_status" not in st.session_state:
    st.session_state.email_status = None
    st.session_state.email_message = ""
if "selected_agent" not in st.session_state:
    st.session_state.selected_agent = None  # Start with no agent selected

# Secrets
XAI_API_KEY = st.secrets["XAI_API_KEY"]
RESEND_API_KEY = st.secrets["RESEND_API_KEY"]
YOUR_EMAIL = st.secrets["YOUR_EMAIL"]

client = OpenAI(api_key=XAI_API_KEY, base_url="https://api.x.ai/v1")

# Updated CSS with full agent cards, consistent alignment, no extra bubbles
st.markdown("""
<style>
    .stApp {
        background: linear-gradient(to bottom, #ffecd2, #fcb69f);
        color: #0c4a6e;
    }
    .main-header { 
        font-size: 3.5rem; 
        color: #ea580c; 
        text-align: center; 
        text-shadow: 2px 2px 4px rgba(0,0,0,0.2); 
        font-weight: bold;
    }
    .tagline { 
        font-size: 2rem; 
        color: #166534; 
        text-align: center; 
        font-style: italic; 
        margin-bottom: 2rem; 
    }
    .agent-card {
        background: rgba(255,255,255,0.95);
        border-radius: 20px;
        padding: 2rem;
        text-align: center;
        box-shadow: 0 8px 16px rgba(0,0,0,0.15);
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    .agent-name {
        font-size: 1.8rem;
        font-weight: bold;
        color: #ea580c;
        margin-bottom: 1rem;
    }
    .agent-desc {
        font-size: 1.1rem;
        line-height: 1.5;
        min-height: 100px;
        margin: 1rem 0;
    }
    .stButton>button {
        background-color: #ea580c;
        color: white;
        border-radius: 15px;
        font-weight: bold;
        font-size: 1.2rem;
        height: 4em;
        width: 100%;
        margin-top: auto;
    }
    /* Remove any unwanted Streamlit backgrounds */
    .stMarkdown { background: transparent !important; }
</style>
""", unsafe_allow_html=True)

st.markdown("<h1 class='main-header'>LBL LIFESTYLE SOLUTIONS</h1>", unsafe_allow_html=True)
st.markdown("<p class='tagline'>LIVE BETTER LONGER</p>", unsafe_allow_html=True)

# Hero image
st.image("https://i.postimg.cc/tgsgw1dW/image.jpg", use_column_width=True, caption="Your Longevity Blueprint")

# === MEET THE LIFESTYLE TEAM ===
st.markdown("### MEET THE LIFESTYLE TEAM")

cols = st.columns(3)

with cols[0]:
    st.markdown("<div class='agent-card'>", unsafe_allow_html=True)
    st.markdown("<div class='agent-name'>FRED</div>", unsafe_allow_html=True)
    st.image("https://i.postimg.cc/MGxQfXtd/austin-distel-h1RW-NFt-Uyc-unsplash.jpg", width=200)
    st.markdown("<div class='agent-desc'><strong>YOUR WELLNESS HOME SCOUT</strong><br>A goal-focused realtor. Let's start by generating a detailed report of home options that match your lifestyle needs.</div>", unsafe_allow_html=True)
    if st.button("CLICK HERE TO GET STARTED", key="fred", use_container_width=True):
        st.session_state.selected_agent = "fred"
    st.markdown("</div>", unsafe_allow_html=True)

with cols[1]:
    st.markdown("<div class='agent-card'>", unsafe_allow_html=True)
    st.markdown("<div class='agent-name'>GREG</div>", unsafe_allow_html=True)
    st.image("https://i.postimg.cc/yxf3Szvc/pexels-andres-ayrton-6551079.jpg", width=200)
    st.markdown("<div class='agent-desc'><strong>YOUR PERSONAL TRAINER</strong><br>A motivated lifestyle coach. Let's start with a workout routine tailored to your fitness goals and health needs.</div>", unsafe_allow_html=True)
    if st.button("CLICK HERE TO GET STARTED", key="greg", use_container_width=True):
        st.session_state.selected_agent = "greg"
    st.markdown("</div>", unsafe_allow_html=True)

with cols[2]:
    st.markdown("<div class='agent-card'>", unsafe_allow_html=True)
    st.markdown("<div class='agent-name'>NURSE ZOEY ZOE</div>", unsafe_allow_html=True)
    st.image("https://images.pexels.com/photos/5215021/pexels-photo-5215021.jpeg", width=200)
    st.markdown("<div class='agent-desc'><strong>YOUR HEALTH ASSESSOR</strong><br>A compassionate wellness guide. Ask Zoey any health question. She can help you develop a proactive health lifestyle.</div>", unsafe_allow_html=True)
    if st.button("CLICK HERE TO GET STARTED", key="zoey", use_container_width=True):
        st.session_state.selected_agent = "zoey"
    st.markdown("</div>", unsafe_allow_html=True)

st.markdown("---")

# Fixed model name to current valid xAI model (as of Dec 2025)
MODEL_NAME = "grok-4-1-fast-reasoning"

# === Agent Content ===
if st.session_state.selected_agent == "fred":
    st.markdown("### 🏡 FRED – Your Wellness Home Scout")
    st.success("**The report generated by this tool is completely free – no cost, no obligation! You will receive five total tailored recommendations. The first two recommendations immediately. You will then receive the full report via email.**")
    st.write("The perfect home that supports your lifestyle awaits.")
    st.image("https://i.postimg.cc/fRms9xv6/tierra-mallorca-rg-J1J8SDEAY-unsplash.jpg", use_column_width=True, caption="Your Keys Await – Welcome to your longevity lifestyle")
    
    client_needs = st.text_area("DESCRIBE YOUR DREAM WELLNESS NEEDS IN DETAIL. LET FRED DO THE REST!!!", height=220, placeholder="Example: Active couple in our 40s, love trails and home workouts, need gym space, near nature, budget $500k...")
    col1, col2 = st.columns(2)
    with col1:
        budget = st.number_input("Maximum budget ($)", min_value=100000, value=500000, step=10000)
    with col2:
        location = st.text_input("Preferred area in Florida", value="Tampa Bay, St. Petersburg, Clearwater, Brandon")
    
    if st.button("🔍 GENERATE MY REPORT", type="primary"):
        if not client_needs.strip():
            st.warning("Please describe your lifestyle needs above!")
        else:
            with st.spinner("Fred is finding your perfect matches..."):
                full_prompt = f"""..."""  # (your existing long prompt here - unchanged)
                try:
                    response = client.chat.completions.create(
                        model=MODEL_NAME,
                        messages=[
                            {"role": "system", "content": "You are Fred, a professional goal-focused real estate advisor."},
                            {"role": "user", "content": full_prompt}
                        ],
                        max_tokens=2000,
                        temperature=0.7
                    )
                    full_report = response.choices[0].message.content
                    # ... rest of teaser parsing and email form unchanged
                except Exception as e:
                    st.error("Fred is reviewing listings... try again soon.")
                    st.caption(f"Note: {str(e)}")

# Similar updates for Greg and Zoey sections (model name only)
elif st.session_state.selected_agent == "greg":
    # ... your Greg section with model=MODEL_NAME
elif st.session_state.selected_agent == "zoey":
    # ... your Zoey section with model=MODEL_NAME

# Footer unchanged
st.markdown("---")
st.markdown("<small>LBL Lifestyle Solutions • Your Holistic Longevity Blueprint<br>Powered by Grok (xAI) • Personalized wellness powered by AI</small>", unsafe_allow_html=True)
